## Preparing data

## Loading Raw IMDb Review Files

The IMDb dataset stores reviews as individual text files organized by sentiment labels in separate directories.

### Train Data

In [1]:
from pathlib import Path
dataset_path_pos=Path("../data/train/pos")
dataset_path_neg=Path("../data/train/neg")

In [2]:
pos_files = list(dataset_path_pos.glob("*.txt"))
neg_files = list(dataset_path_neg.glob("*.txt"))
print(len(pos_files))

12500

In [3]:
sample_file=pos_files[0]
text=sample_file.read_text(encoding='utf-8')
print(text[:100])

Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life,

In [4]:
# Reading all the Review from the .txt file 
def read_review(files): 
    reviews=[]
    for file in files:
        text=file.read_text(encoding='utf-8')
        reviews.append(text)
    return reviews

In [5]:
pos_review=read_review(pos_files)

In [6]:
neg_review=read_review(neg_files)

In [7]:
# The data is stored in list with the review type
def store_data(reviews,rev_type):
    data=[]
    for review in reviews:
        data.append({"review": review,
                    "sentiment":rev_type})
    return data

In [8]:
pos_data=store_data(pos_review,"positive")
neg_data=store_data(neg_review,"negative")

In [9]:
all_data=pos_data+neg_data

In [10]:
import pandas as pd 
df= pd.DataFrame(all_data)

In [11]:
df=df.sample(frac=1,random_state=42).reset_index(drop=True)

In [12]:
df

                                                  review sentiment
0      In Panic In The Streets Richard Widmark plays ...  positive
1      If you ask me the first one was really better ...  negative
2      I am a big fan a Faerie Tale Theatre and I've ...  positive
3      I just finished reading a book about Dillinger...  negative
4      Greg Davis and Bryan Daly take some crazed sta...  negative
...                                                  ...       ...
24995  My roommates & I nearly shorted out our TV fro...  negative
24996  Michelle Rodriguez is the defining actress who...  positive
24997  Nice movie with a great soundtrack which spans...  positive
24998  Even though this was a made-for-TV production,...  negative
24999  I saw this on cable recently and kinda enjoyed...  negative

[25000 rows x 2 columns]

In [13]:
df.head()

                                              review sentiment
0  In Panic In The Streets Richard Widmark plays ...  positive
1  If you ask me the first one was really better ...  negative
2  I am a big fan a Faerie Tale Theatre and I've ...  positive
3  I just finished reading a book about Dillinger...  negative
4  Greg Davis and Bryan Daly take some crazed sta...  negative

In [14]:
df['sentiment'].value_counts()

sentiment
positive    12500
negative    12500
Name: count, dtype: int64

In [15]:
df.sample(10)

                                                  review sentiment
10776  I've watched this movie twice now on DVD, and ...  positive
11899  In this forgettable trifle, the 40-ish Norma S...  negative
12982  I thought that Zombie Flesh Eaters 2 was quite...  negative
23038  Water Lilies is a well-made first film from Fr...  positive
7598   Well I'm probably about to be lambasted by eve...  negative
14466  This is a great movie but there could be more ...  positive
3949   The significance of French title of this film,...  positive
21728  Actually, Goldie Hawn is from Washington (Tako...  positive
5245   Well, if it weren't for Ethel Waters and a 7-y...  negative
6469   This, "Prodigal Son" and "Eastern Condors" are...  positive

In [16]:
df.to_csv("../data/train.csv")

### Test Data

In [17]:
dataset_path_test_pos=Path("../data/test/pos")
dataset_path_test_neg=Path("../data/test/neg")

In [18]:
test_pos=list(dataset_path_test_pos.glob("**.txt"))
test_neg=list(dataset_path_test_neg.glob("**.txt"))

In [19]:
test_pos_review=read_review(test_pos)

In [20]:
test_neg_review=read_review(test_neg)

In [21]:
test_data_pos=store_data(test_pos_review,"positive")
test_data_neg=store_data(test_neg_review,"negative")

In [22]:
all_test_data=test_data_pos+test_data_neg

In [23]:
test_df=pd.DataFrame(all_test_data)

In [24]:
test_df=test_df.sample(frac=1,random_state=42).reset_index(drop=True)

In [25]:
test_df.head()

                                              review sentiment
0  When I was a kid, I loved "Tiny Toons". I espe...  positive
1  The setup for "Nature of the Beast" is ingenio...  negative
2  I do not have much to say than this is a great...  positive
3  Extremely formulaic with cosmic-sized logic ho...  negative
4  I actually liked certain things about this gam...  negative

In [26]:
test_df.to_csv("../data/test.csv")

In [27]:
sample_review=df["review"][0]