## Preparing data

In [31]:
from pathlib import Path
dataset_path_pos=Path("../data/train/pos")
dataset_path_neg=Path("../data/train/neg")

In [32]:
pos_files = list(dataset_path_pos.glob("*.txt"))
neg_files = list(dataset_path_neg.glob("*.txt"))


print(len(pos_files))

12500

In [33]:
sample_file=pos_files[0]
text=sample_file.read_text(encoding='utf-8')
print(text[:100])

Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life,

In [ ]:
# Reading all the Review from the .txt file 
def read_review(files): 
    reviews=[]
    for file in files:
        text=file.read_text(encoding='utf-8')
        reviews.append(text)
    return reviews

In [34]:
pos_review=read_review(pos_files)

In [36]:
neg_review=read_review(neg_files)

In [ ]:
# The data is stored in list with the review type
def store_data(reviews,rev_type):
    data=[]
    for review in reviews:
        data.append({"review": review,
                    "sentiment":rev_type})
    return data

In [44]:
pos_data=store_data(pos_review,"positive")
neg_data=store_data(neg_review,"negative")

In [47]:
all_data=pos_data+neg_data

In [59]:
import pandas as pd 
df= pd.DataFrame(all_data)

In [60]:
df=df.sample(frac=1,random_state=42).reset_index(drop=True)

In [61]:
df

                                                  review sentiment
0      In Panic In The Streets Richard Widmark plays ...  positive
1      If you ask me the first one was really better ...  negative
2      I am a big fan a Faerie Tale Theatre and I've ...  positive
3      I just finished reading a book about Dillinger...  negative
4      Greg Davis and Bryan Daly take some crazed sta...  negative
...                                                  ...       ...
24995  My roommates & I nearly shorted out our TV fro...  negative
24996  Michelle Rodriguez is the defining actress who...  positive
24997  Nice movie with a great soundtrack which spans...  positive
24998  Even though this was a made-for-TV production,...  negative
24999  I saw this on cable recently and kinda enjoyed...  negative

[25000 rows x 2 columns]

In [62]:
df.head()

                                              review sentiment
0  In Panic In The Streets Richard Widmark plays ...  positive
1  If you ask me the first one was really better ...  negative
2  I am a big fan a Faerie Tale Theatre and I've ...  positive
3  I just finished reading a book about Dillinger...  negative
4  Greg Davis and Bryan Daly take some crazed sta...  negative