# Text preprocessing

## Importing data

In [213]:
import pandas as pd
from pathlib import Path
dataset_path=("../data/train.csv")

In [214]:
df=pd.read_csv(dataset_path,index_col=0)

In [215]:
df.head()

                                              review sentiment
0  In Panic In The Streets Richard Widmark plays ...  positive
1  If you ask me the first one was really better ...  negative
2  I am a big fan a Faerie Tale Theatre and I've ...  positive
3  I just finished reading a book about Dillinger...  negative
4  Greg Davis and Bryan Daly take some crazed sta...  negative

In [216]:
df.columns

Index(['review', 'sentiment'], dtype='str')

In [217]:
sample_review=df['review'][0]

In [218]:
sample_review.lower()

"in panic in the streets richard widmark plays u.s. navy doctor who has his week rudely interrupted with a corpse that contains plague. as cop paul douglas properly points out the guy died from two bullets in the chest. that's not the issue here, the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the disease.<br /><br />as was pointed out by any number of people, for some reason director elia kazan did not bother to cast the small parts with anyone that sounds like they're from louisiana. having been to new orleans where the story takes place i can personally attest to that. richard widmark and his wife barbara bel geddes can be excused because as a navy doctor he could be assigned there, but for those that are natives it doesn't work.<br /><br />but with plague out there and the news being kept a secret, the new orleans pd starts a dragnet of the city's underworld. the dead guy came off a ship from europe and he had underworld connections. a new orleans wise guy played by jack palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms. palance got rave reviews in the first film where he received notice.<br /><br />personally my favorite in this film is zero mostel. this happened right before mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies. he plays the same kind of role in the humphrey bogart film, the enforcer. sadly i can kind of identify with mostel in that last chase scene where he and palance are being chased down by widmark, douglas, and half the new orleans police. seeing the weight challenged zero trying to keep up with palance was something else because i'm kind of in zero's league now in the heft department.<br /><br />kazan kept the action going at a good clip, there's very little down time in this film. if there was any less it would be an indiana jones film. panic in the streets won an oscar for best original screenplay that year.<br /><br />kazan also made good use of the new orleans waterfront and the french quarter. some of the same kinds of shots are later used in on the waterfront. in fact panic in the streets is about people not squealing when they really should in their own best interest. very similar again to on the waterfront.<br /><br />panic in the streets does everyone proud who was associated with it. now why couldn't elia kazan get some decent new orleans sounding people in the small roles."

### HTML Removal

In [219]:
import regex as re

In [223]:
def html_remover(text):
    if isinstance(text,str):
        return re.sub(r"<.*?>","",text)
    return text

In [224]:
df['review']=df['review'].apply(html_remover)

In [225]:
df['review'][0]

"In Panic In The Streets Richard Widmark plays U.S. Navy doctor who has his week rudely interrupted with a corpse that contains plague. As cop Paul Douglas properly points out the guy died from two bullets in the chest. That's not the issue here, the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the disease.As was pointed out by any number of people, for some reason director Elia Kazan did not bother to cast the small parts with anyone that sounds like they're from Louisiana. Having been to New Orleans where the story takes place I can personally attest to that. Richard Widmark and his wife Barbara Bel Geddes can be excused because as a Navy doctor he could be assigned there, but for those that are natives it doesn't work.But with plague out there and the news being kept a secret, the New Orleans PD starts a dragnet of the city's underworld. The dead guy came off a ship from Europe and he had underworld connections. A New Orleans wise guy played by Jack Palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms. Palance got rave reviews in the first film where he received notice.Personally my favorite in this film is Zero Mostel. This happened right before Mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies. He plays the same kind of role in the Humphrey Bogart film, The Enforcer. Sadly I can kind of identify with Mostel in that last chase scene where he and Palance are being chased down by Widmark, Douglas, and half the New Orleans Police. Seeing the weight challenged Zero trying to keep up with Palance was something else because I'm kind of in Zero's league now in the heft department.Kazan kept the action going at a good clip, there's very little down time in this film. If there was any less it would be an Indiana Jones film. Panic In The Streets won an Oscar for Best Original Screenplay that year.Kazan also made good use of the New Orleans waterfront and the French Quarter. Some of the same kinds of shots are later used in On the Waterfront. In fact Panic In The Streets is about people not squealing when they really should in their own best interest. Very similar again to On the Waterfront.Panic In The Streets does everyone proud who was associated with it. Now why couldn't Elia Kazan get some decent New Orleans sounding people in the small roles."

In [226]:
import string
def punc_clean(text):
    pun=string.punctuation
    samp_tex=str()
    for i in text:
        if i not in pun:
            samp_tex += i 
    return samp_tex

In [233]:
df['review']=df['review'].apply(punc_clean)

## Tokenization

In [234]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('punkt')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Seetharaman\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Seetharaman\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [235]:
def toke(text):
    tokens=word_tokenize(text)
    return tokens

In [236]:
df['clean_review']=df['review'].apply(toke)

In [237]:
df = df[['review', 'clean_review', 'sentiment']]

In [238]:
df.sample(5)

                                                  review  ... sentiment
1585   An unusual take on time travel instead of trav...  ...  positive
21273  actually it was pretty funny in a god how the ...  ...  negative
1471   Do not see this movie if you value your mind A...  ...  negative
19522  When I tell people that I review movies as a h...  ...  negative
7226   Despite a tight narrative Johnnie Tos Election...  ...  positive

[5 rows x 3 columns]

## Stop words

In [239]:
from nltk.corpus import stopwords

In [240]:
stop_words=set(stopwords.words('english'))
stop_words.remove('not')
stop_words.remove('no')
stop_words.remove('nor')

In [241]:
def stop_word(text):
    # stop_words=set(stopwords.words('english'))
    filtered=[
        word for word in text
        if word.lower() not in stop_words
    ]
    return filtered

In [242]:
df['clean_review']=df['clean_review'].apply(stop_word)

In [243]:
df['clean_review']

0        [Panic, Streets, Richard, Widmark, plays, US, ...
1        [ask, first, one, really, better, one, Look, S...
2        [big, fan, Faerie, Tale, Theatre, Ive, seen, o...
3        [finished, reading, book, Dillinger, movie, ho...
4        [Greg, Davis, Bryan, Daly, take, crazed, state...
                               ...
24995    [roommates, nearly, shorted, TV, numerous, spi...
24996    [Michelle, Rodriguez, defining, actress, could...
24997    [Nice, movie, great, soundtrack, spans, rock, ...
24998    [Even, though, madeforTV, production, theres, ...
24999    [saw, cable, recently, kinda, enjoyed, Ive, re...
Name: clean_review, Length: 25000, dtype: object

## Lemmatization

In [244]:
from nltk.stem import WordNetLemmatizer
def lemmatization(lis):
    lemmatizer=WordNetLemmatizer()
    l=list()
    for word in lis:
        a=lemmatizer.lemmatize(word)
        l.append(a)
    return l

In [ ]:
df['clean_review']=df['clean_review'].apply(lemmatization)

In [247]:
df['clean_review'][0]

['Panic',
 'Streets',
 'Richard',
 'Widmark',
 'play',
 'US',
 'Navy',
 'doctor',
 'week',
 'rudely',
 'interrupted',
 'corpse',
 'contains',
 'plague',
 'cop',
 'Paul',
 'Douglas',
 'properly',
 'point',
 'guy',
 'died',
 'two',
 'bullet',
 'chest',
 'Thats',
 'not',
 'issue',
 'two',
 'become',
 'unwilling',
 'partner',
 'effort',
 'find',
 'killer',
 'anyone',
 'else',
 'exposed',
 'diseaseAs',
 'pointed',
 'number',
 'people',
 'reason',
 'director',
 'Elia',
 'Kazan',
 'not',
 'bother',
 'cast',
 'small',
 'part',
 'anyone',
 'sound',
 'like',
 'theyre',
 'Louisiana',
 'New',
 'Orleans',
 'story',
 'take',
 'place',
 'personally',
 'attest',
 'Richard',
 'Widmark',
 'wife',
 'Barbara',
 'Bel',
 'Geddes',
 'excused',
 'Navy',
 'doctor',
 'could',
 'assigned',
 'native',
 'doesnt',
 'workBut',
 'plague',
 'news',
 'kept',
 'secret',
 'New',
 'Orleans',
 'PD',
 'start',
 'dragnet',
 'city',
 'underworld',
 'dead',
 'guy',
 'came',
 'ship',
 'Europe',
 'underworld',
 'connection',
 'New',
 'Orleans',
 'wise',
 'guy',
 'played',
 'Jack',
 'Palance',
 'jump',
 'whole',
 'bunch',
 'erroneous',
 'conclusion',
 'start',
 'harassing',
 'cousin',
 'dead',
 'guy',
 'starting',
 'show',
 'plague',
 'symptom',
 'Palance',
 'got',
 'rave',
 'review',
 'first',
 'film',
 'received',
 'noticePersonally',
 'favorite',
 'film',
 'Zero',
 'Mostel',
 'happened',
 'right',
 'Mostel',
 'blacklisted',
 'around',
 'time',
 'made',
 'specialty',
 'playing',
 'would',
 'tough',
 'guy',
 'really',
 'toady',
 'play',
 'kind',
 'role',
 'Humphrey',
 'Bogart',
 'film',
 'Enforcer',
 'Sadly',
 'kind',
 'identify',
 'Mostel',
 'last',
 'chase',
 'scene',
 'Palance',
 'chased',
 'Widmark',
 'Douglas',
 'half',
 'New',
 'Orleans',
 'Police',
 'Seeing',
 'weight',
 'challenged',
 'Zero',
 'trying',
 'keep',
 'Palance',
 'something',
 'else',
 'Im',
 'kind',
 'Zeros',
 'league',
 'heft',
 'departmentKazan',
 'kept',
 'action',
 'going',
 'good',
 'clip',
 'there',
 'little',
 'time',
 'film',
 'less',
 'would',
 'Indiana',
 'Jones',
 'film',
 'Panic',
 'Streets',
 'Oscar',
 'Best',
 'Original',
 'Screenplay',
 'yearKazan',
 'also',
 'made',
 'good',
 'use',
 'New',
 'Orleans',
 'waterfront',
 'French',
 'Quarter',
 'kind',
 'shot',
 'later',
 'used',
 'Waterfront',
 'fact',
 'Panic',
 'Streets',
 'people',
 'not',
 'squealing',
 'really',
 'best',
 'interest',
 'similar',
 'WaterfrontPanic',
 'Streets',
 'everyone',
 'proud',
 'associated',
 'couldnt',
 'Elia',
 'Kazan',
 'get',
 'decent',
 'New',
 'Orleans',
 'sounding',
 'people',
 'small',
 'role']

In [248]:
df.head()

                                              review  ... sentiment
0  In Panic In The Streets Richard Widmark plays ...  ...  positive
1  If you ask me the first one was really better ...  ...  negative
2  I am a big fan a Faerie Tale Theatre and Ive s...  ...  positive
3  I just finished reading a book about Dillinger...  ...  negative
4  Greg Davis and Bryan Daly take some crazed sta...  ...  negative

[5 rows x 3 columns]

## TF-IDF

In [249]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [250]:
df['clean_review']=df['clean_review'].apply(lambda x:" ".join(x))

In [252]:
df['clean_review']

0        Panic Streets Richard Widmark play US Navy doc...
1        ask first one really better one Look Sarah G r...
2        big fan Faerie Tale Theatre Ive seen one best ...
3        finished reading book Dillinger movie horribly...
4        Greg Davis Bryan Daly take crazed statement te...
                               ...
24995    roommate nearly shorted TV numerous spittakes ...
24996    Michelle Rodriguez defining actress could char...
24997    Nice movie great soundtrack span rock landscap...
24998    Even though madeforTV production there absolut...
24999    saw cable recently kinda enjoyed Ive reading c...
Name: clean_review, Length: 25000, dtype: str

In [253]:
tfidf=TfidfVectorizer(max_features=5000)

X=tfidf.fit_transform(df['clean_review'])

In [254]:
y=df['sentiment']

## Train and Test split

In [255]:
from sklearn.model_selection import train_test_split

In [256]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42, test_size=0.1)

In [257]:
X_train.shape

(22500, 5000)

## Training Model

In [258]:
from sklearn.linear_model import LogisticRegression

In [259]:
lr_model=LogisticRegression(max_iter=1000)

In [260]:
lr_model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [261]:
y_pred=lr_model.predict(X_test)

In [262]:
y_pred.shape

(2500,)

In [264]:
y_test

6868     positive
24016    negative
9668     positive
13640    negative
14018    positive
           ...
20854    positive
15308    negative
13238    positive
21567    negative
11393    positive
Name: sentiment, Length: 2500, dtype: str

In [199]:
df['sentiment'].value_counts()

sentiment
positive    12500
negative    12500
Name: count, dtype: int64

In [265]:
y_pred[:50]

array(['positive', 'negative', 'positive', 'negative', 'positive',
       'positive', 'positive', 'positive', 'negative', 'negative',
       'positive', 'positive', 'positive', 'negative', 'positive',
       'negative', 'negative', 'positive', 'negative', 'negative',
       'negative', 'negative', 'positive', 'positive', 'positive',
       'positive', 'positive', 'negative', 'positive', 'negative',
       'negative', 'negative', 'negative', 'negative', 'positive',
       'positive', 'negative', 'positive', 'positive', 'negative',
       'negative', 'negative', 'positive', 'negative', 'negative',
       'positive', 'positive', 'negative', 'positive', 'negative'],
      dtype=object)

0.8896

In [309]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

In [310]:
from src.preprocessing import preprocessing
new_review = "This movie was amazing"

cleaned = preprocessing(new_review)

In [311]:
cleaned