# Text preprocessing

## Importing data

In [97]:
import pandas as pd
from pathlib import Path
dataset_path=("../data/train.csv")

In [98]:
df=pd.read_csv(dataset_path,index_col=0)

In [99]:
df.head()

                                              review sentiment
0  In Panic In The Streets Richard Widmark plays ...  positive
1  If you ask me the first one was really better ...  negative
2  I am a big fan a Faerie Tale Theatre and I've ...  positive
3  I just finished reading a book about Dillinger...  negative
4  Greg Davis and Bryan Daly take some crazed sta...  negative

In [100]:
df.columns

Index(['review', 'sentiment'], dtype='str')

In [101]:
sample_review=df['review'][0]

In [102]:
sample_review.lower()

"in panic in the streets richard widmark plays u.s. navy doctor who has his week rudely interrupted with a corpse that contains plague. as cop paul douglas properly points out the guy died from two bullets in the chest. that's not the issue here, the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the disease.<br /><br />as was pointed out by any number of people, for some reason director elia kazan did not bother to cast the small parts with anyone that sounds like they're from louisiana. having been to new orleans where the story takes place i can personally attest to that. richard widmark and his wife barbara bel geddes can be excused because as a navy doctor he could be assigned there, but for those that are natives it doesn't work.<br /><br />but with plague out there and the news being kept a secret, the new orleans pd starts a dragnet of the city's underworld. the dead guy came off a ship from europe and he had underworld connections. a new orleans wise guy played by jack palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms. palance got rave reviews in the first film where he received notice.<br /><br />personally my favorite in this film is zero mostel. this happened right before mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies. he plays the same kind of role in the humphrey bogart film, the enforcer. sadly i can kind of identify with mostel in that last chase scene where he and palance are being chased down by widmark, douglas, and half the new orleans police. seeing the weight challenged zero trying to keep up with palance was something else because i'm kind of in zero's league now in the heft department.<br /><br />kazan kept the action going at a good clip, there's very little down time in this film. if there was any less it would be an indiana jones film. panic in the streets won an oscar for best original screenplay that year.<br /><br />kazan also made good use of the new orleans waterfront and the french quarter. some of the same kinds of shots are later used in on the waterfront. in fact panic in the streets is about people not squealing when they really should in their own best interest. very similar again to on the waterfront.<br /><br />panic in the streets does everyone proud who was associated with it. now why couldn't elia kazan get some decent new orleans sounding people in the small roles."

### HTML Removal

In [103]:
import regex as re

In [104]:
def html_remover(text):
    if isinstance(text,str):
        return re.sub(r"<.*?>","",text)
    return text

In [105]:
df['review']=df['review'].apply(html_remover)

In [106]:
df['review'][0]

"In Panic In The Streets Richard Widmark plays U.S. Navy doctor who has his week rudely interrupted with a corpse that contains plague. As cop Paul Douglas properly points out the guy died from two bullets in the chest. That's not the issue here, the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the disease.As was pointed out by any number of people, for some reason director Elia Kazan did not bother to cast the small parts with anyone that sounds like they're from Louisiana. Having been to New Orleans where the story takes place I can personally attest to that. Richard Widmark and his wife Barbara Bel Geddes can be excused because as a Navy doctor he could be assigned there, but for those that are natives it doesn't work.But with plague out there and the news being kept a secret, the New Orleans PD starts a dragnet of the city's underworld. The dead guy came off a ship from Europe and he had underworld connections. A New Orleans wise guy played by Jack Palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms. Palance got rave reviews in the first film where he received notice.Personally my favorite in this film is Zero Mostel. This happened right before Mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies. He plays the same kind of role in the Humphrey Bogart film, The Enforcer. Sadly I can kind of identify with Mostel in that last chase scene where he and Palance are being chased down by Widmark, Douglas, and half the New Orleans Police. Seeing the weight challenged Zero trying to keep up with Palance was something else because I'm kind of in Zero's league now in the heft department.Kazan kept the action going at a good clip, there's very little down time in this film. If there was any less it would be an Indiana Jones film. Panic In The Streets won an Oscar for Best Original Screenplay that year.Kazan also made good use of the New Orleans waterfront and the French Quarter. Some of the same kinds of shots are later used in On the Waterfront. In fact Panic In The Streets is about people not squealing when they really should in their own best interest. Very similar again to On the Waterfront.Panic In The Streets does everyone proud who was associated with it. Now why couldn't Elia Kazan get some decent New Orleans sounding people in the small roles."

In [107]:
import string
def punc_clean(text):
    pun=string.punctuation
    samp_tex=str()
    for i in text:
        if i not in pun:
            samp_tex += i 
    return samp_tex

In [108]:
df['review']=df['review'].apply(punc_clean)

## Tokenization

In [109]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('punkt')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Seetharaman\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Seetharaman\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [110]:
def toke(text):
    tokens=word_tokenize(text)
    return tokens

In [128]:
df['clean_review']=df['review'].apply(toke)

In [129]:
df = df[['review', 'clean_review', 'sentiment']]

In [113]:
df.sample(5)

,review,clean_review,sentiment
9219,Who would think Andy Griffiths Helen Crump Ane...,"[Who, would, think, Andy, Griffiths, Helen, Cr...",positive
22342,Im afraid that youll find that the huge majori...,"[Im, afraid, that, youll, find, that, the, hug...",negative
4852,A young woman unwittingly becomes part of a ki...,"[A, young, woman, unwittingly, becomes, part, ...",negative
8479,Ive also been looking to find this movie for q...,"[Ive, also, been, looking, to, find, this, mov...",positive
23201,Please help the economy spend your money else...,"[Please, help, the, economy, spend, your, mone...",negative

## Stop words

In [130]:
from nltk.corpus import stopwords

In [131]:
stop_words=set(stopwords.words('english'))
stop_words.remove('not')
stop_words.remove('no')
stop_words.remove('nor')

In [132]:
def stop_word(text):
    # stop_words=set(stopwords.words('english'))
    filtered=[
        word for word in text
        if word.lower() not in stop_words
    ]
    return filtered

In [133]:
df['clean_review']=df['clean_review'].apply(stop_word)

In [134]:
df['clean_review']

0        [Panic, Streets, Richard, Widmark, plays, US, ...
1        [ask, first, one, really, better, one, Look, S...
2        [big, fan, Faerie, Tale, Theatre, Ive, seen, o...
3        [finished, reading, book, Dillinger, movie, ho...
4        [Greg, Davis, Bryan, Daly, take, crazed, state...
                               ...
24995    [roommates, nearly, shorted, TV, numerous, spi...
24996    [Michelle, Rodriguez, defining, actress, could...
24997    [Nice, movie, great, soundtrack, spans, rock, ...
24998    [Even, though, madeforTV, production, theres, ...
24999    [saw, cable, recently, kinda, enjoyed, Ive, re...
Name: clean_review, Length: 25000, dtype: object

## Lemmatization

In [119]:
from nltk.stem import WordNetLemmatizer
def lemmatization(lis):
    lemmatizer=WordNetLemmatizer()
    l=list()
    for word in lis:
        a=lemmatizer.lemmatize(word)
        l.append(a)
    return l

In [120]:
df['clean_review']=df['clean_review'].apply(lemmatization)

In [121]:
df['clean_review'][0]

['Panic',
 'Streets',
 'Richard',
 'Widmark',
 'play',
 'US',
 'Navy',
 'doctor',
 'week',
 'rudely',
 'interrupted',
 'corpse',
 'contains',
 'plague',
 'cop',
 'Paul',
 'Douglas',
 'properly',
 'point',
 'guy',
 'died',
 'two',
 'bullet',
 'chest',
 'Thats',
 'not',
 'issue',
 'two',
 'become',
 'unwilling',
 'partner',
 'effort',
 'find',
 'killer',
 'anyone',
 'else',
 'exposed',
 'diseaseAs',
 'pointed',
 'number',
 'people',
 'reason',
 'director',
 'Elia',
 'Kazan',
 'not',
 'bother',
 'cast',
 'small',
 'part',
 'anyone',
 'sound',
 'like',
 'theyre',
 'Louisiana',
 'New',
 'Orleans',
 'story',
 'take',
 'place',
 'personally',
 'attest',
 'Richard',
 'Widmark',
 'wife',
 'Barbara',
 'Bel',
 'Geddes',
 'excused',
 'Navy',
 'doctor',
 'could',
 'assigned',
 'native',
 'doesnt',
 'workBut',
 'plague',
 'news',
 'kept',
 'secret',
 'New',
 'Orleans',
 'PD',
 'start',
 'dragnet',
 'city',
 'underworld',
 'dead',
 'guy',
 'came',
 'ship',
 'Europe',
 'underworld',
 'connection',
 'New',
 'Orleans',
 'wise',
 'guy',
 'played',
 'Jack',
 'Palance',
 'jump',
 'whole',
 'bunch',
 'erroneous',
 'conclusion',
 'start',
 'harassing',
 'cousin',
 'dead',
 'guy',
 'starting',
 'show',
 'plague',
 'symptom',
 'Palance',
 'got',
 'rave',
 'review',
 'first',
 'film',
 'received',
 'noticePersonally',
 'favorite',
 'film',
 'Zero',
 'Mostel',
 'happened',
 'right',
 'Mostel',
 'blacklisted',
 'around',
 'time',
 'made',
 'specialty',
 'playing',
 'would',
 'tough',
 'guy',
 'really',
 'toady',
 'play',
 'kind',
 'role',
 'Humphrey',
 'Bogart',
 'film',
 'Enforcer',
 'Sadly',
 'kind',
 'identify',
 'Mostel',
 'last',
 'chase',
 'scene',
 'Palance',
 'chased',
 'Widmark',
 'Douglas',
 'half',
 'New',
 'Orleans',
 'Police',
 'Seeing',
 'weight',
 'challenged',
 'Zero',
 'trying',
 'keep',
 'Palance',
 'something',
 'else',
 'Im',
 'kind',
 'Zeros',
 'league',
 'heft',
 'departmentKazan',
 'kept',
 'action',
 'going',
 'good',
 'clip',
 'there',
 'little',
 'time',
 'film',
 'less',
 'would',
 'Indiana',
 'Jones',
 'film',
 'Panic',
 'Streets',
 'Oscar',
 'Best',
 'Original',
 'Screenplay',
 'yearKazan',
 'also',
 'made',
 'good',
 'use',
 'New',
 'Orleans',
 'waterfront',
 'French',
 'Quarter',
 'kind',
 'shot',
 'later',
 'used',
 'Waterfront',
 'fact',
 'Panic',
 'Streets',
 'people',
 'not',
 'squealing',
 'really',
 'best',
 'interest',
 'similar',
 'WaterfrontPanic',
 'Streets',
 'everyone',
 'proud',
 'associated',
 'couldnt',
 'Elia',
 'Kazan',
 'get',
 'decent',
 'New',
 'Orleans',
 'sounding',
 'people',
 'small',
 'role']

In [125]:
df.head()
df['clean_review']=df['clean_review'].apply(lambda x:" ".join(x))

In [126]:
def low(text):
    return text.lower()
df['clean_review']= df['clean_review'].apply(low)

In [127]:
df.to_csv("../data/cleaned.csv")