# Text preprocessing

## Importing data

In [1]:
import pandas as pd
from pathlib import Path
dataset_path=("../data/train.csv")

In [73]:
df=pd.read_csv(dataset_path,index_col=0)

In [74]:
df.head()

                                              review sentiment
0  In Panic In The Streets Richard Widmark plays ...  positive
1  If you ask me the first one was really better ...  negative
2  I am a big fan a Faerie Tale Theatre and I've ...  positive
3  I just finished reading a book about Dillinger...  negative
4  Greg Davis and Bryan Daly take some crazed sta...  negative

In [75]:
df.columns

Index(['review', 'sentiment'], dtype='str')

In [76]:
sample_review=df['review'][0]

In [77]:
sample_review.lower()

"in panic in the streets richard widmark plays u.s. navy doctor who has his week rudely interrupted with a corpse that contains plague. as cop paul douglas properly points out the guy died from two bullets in the chest. that's not the issue here, the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the disease.<br /><br />as was pointed out by any number of people, for some reason director elia kazan did not bother to cast the small parts with anyone that sounds like they're from louisiana. having been to new orleans where the story takes place i can personally attest to that. richard widmark and his wife barbara bel geddes can be excused because as a navy doctor he could be assigned there, but for those that are natives it doesn't work.<br /><br />but with plague out there and the news being kept a secret, the new orleans pd starts a dragnet of the city's underworld. the dead guy came off a ship from europe and he had underworld connections. a new orleans wise guy played by jack palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms. palance got rave reviews in the first film where he received notice.<br /><br />personally my favorite in this film is zero mostel. this happened right before mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies. he plays the same kind of role in the humphrey bogart film, the enforcer. sadly i can kind of identify with mostel in that last chase scene where he and palance are being chased down by widmark, douglas, and half the new orleans police. seeing the weight challenged zero trying to keep up with palance was something else because i'm kind of in zero's league now in the heft department.<br /><br />kazan kept the action going at a good clip, there's very little down time in this film. if there was any less it would be an indiana jones film. panic in the streets won an oscar for best original screenplay that year.<br /><br />kazan also made good use of the new orleans waterfront and the french quarter. some of the same kinds of shots are later used in on the waterfront. in fact panic in the streets is about people not squealing when they really should in their own best interest. very similar again to on the waterfront.<br /><br />panic in the streets does everyone proud who was associated with it. now why couldn't elia kazan get some decent new orleans sounding people in the small roles."

### HTML Removal

In [78]:
import regex as re

In [79]:
def html_remover(text):
    if isinstance(text,str):
        return re.sub(r"<.*?>","",text)
    return text

In [80]:
df['review']=df['review'].apply(html_remover)

In [83]:
df['review'][0]

"In Panic In The Streets Richard Widmark plays U.S. Navy doctor who has his week rudely interrupted with a corpse that contains plague. As cop Paul Douglas properly points out the guy died from two bullets in the chest. That's not the issue here, the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the disease.As was pointed out by any number of people, for some reason director Elia Kazan did not bother to cast the small parts with anyone that sounds like they're from Louisiana. Having been to New Orleans where the story takes place I can personally attest to that. Richard Widmark and his wife Barbara Bel Geddes can be excused because as a Navy doctor he could be assigned there, but for those that are natives it doesn't work.But with plague out there and the news being kept a secret, the New Orleans PD starts a dragnet of the city's underworld. The dead guy came off a ship from Europe and he had underworld connections. A New Orleans wise guy played by Jack Palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms. Palance got rave reviews in the first film where he received notice.Personally my favorite in this film is Zero Mostel. This happened right before Mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies. He plays the same kind of role in the Humphrey Bogart film, The Enforcer. Sadly I can kind of identify with Mostel in that last chase scene where he and Palance are being chased down by Widmark, Douglas, and half the New Orleans Police. Seeing the weight challenged Zero trying to keep up with Palance was something else because I'm kind of in Zero's league now in the heft department.Kazan kept the action going at a good clip, there's very little down time in this film. If there was any less it would be an Indiana Jones film. Panic In The Streets won an Oscar for Best Original Screenplay that year.Kazan also made good use of the New Orleans waterfront and the French Quarter. Some of the same kinds of shots are later used in On the Waterfront. In fact Panic In The Streets is about people not squealing when they really should in their own best interest. Very similar again to On the Waterfront.Panic In The Streets does everyone proud who was associated with it. Now why couldn't Elia Kazan get some decent New Orleans sounding people in the small roles."

In [122]:
import string
def punc_clean(text):
    pun=string.punctuation
    samp_tex=str()
    for i in text:
        if i not in pun:
            samp_tex += i 
    return samp_tex

In [123]:
df['review']=df['review'].apply(punc_clean)

In [125]:
df['review'][0]

'In Panic In The Streets Richard Widmark plays US Navy doctor who has his week rudely interrupted with a corpse that contains plague As cop Paul Douglas properly points out the guy died from two bullets in the chest Thats not the issue here the two of them become unwilling partners in an effort to find the killers and anyone else exposed to the diseaseAs was pointed out by any number of people for some reason director Elia Kazan did not bother to cast the small parts with anyone that sounds like theyre from Louisiana Having been to New Orleans where the story takes place I can personally attest to that Richard Widmark and his wife Barbara Bel Geddes can be excused because as a Navy doctor he could be assigned there but for those that are natives it doesnt workBut with plague out there and the news being kept a secret the New Orleans PD starts a dragnet of the citys underworld The dead guy came off a ship from Europe and he had underworld connections A New Orleans wise guy played by Jack Palance jumps to a whole bunch of erroneous conclusions and starts harassing a cousin of the dead guy who is starting to show plague symptoms Palance got rave reviews in the first film where he received noticePersonally my favorite in this film is Zero Mostel This happened right before Mostel was blacklisted and around that time he made a specialty of playing would be tough guys who are really toadies He plays the same kind of role in the Humphrey Bogart film The Enforcer Sadly I can kind of identify with Mostel in that last chase scene where he and Palance are being chased down by Widmark Douglas and half the New Orleans Police Seeing the weight challenged Zero trying to keep up with Palance was something else because Im kind of in Zeros league now in the heft departmentKazan kept the action going at a good clip theres very little down time in this film If there was any less it would be an Indiana Jones film Panic In The Streets won an Oscar for Best Original Screenplay that yearKazan also made good use of the New Orleans waterfront and the French Quarter Some of the same kinds of shots are later used in On the Waterfront In fact Panic In The Streets is about people not squealing when they really should in their own best interest Very similar again to On the WaterfrontPanic In The Streets does everyone proud who was associated with it Now why couldnt Elia Kazan get some decent New Orleans sounding people in the small roles'

## Tokenization

In [150]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('punkt')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Seetharaman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Seetharaman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [151]:
def toke(text):
    tokens=word_tokenize(text)
    return tokens

In [152]:
df['clean_review']=df['review'].apply(toke)

In [154]:
df = df[['review', 'clean_review', 'sentiment']]

In [157]:
df.sample(5)

,review,clean_review,sentiment
2504,While being an impressionable youth when first...,"[While, being, an, impressionable, youth, when...",positive
23969,I was never a big fan of television until I wa...,"[I, was, never, a, big, fan, of, television, u...",positive
10926,Holes was a GREAT movie Disney made the right ...,"[Holes, was, a, GREAT, movie, Disney, made, th...",positive
14281,Ive watched almost all of the GundamMech anime...,"[Ive, watched, almost, all, of, the, GundamMec...",positive
8096,Having seen men Behind the Sun I guess I hoped...,"[Having, seen, men, Behind, the, Sun, I, guess...",negative

## Stop words

In [159]:
from nltk.corpus import stopwords

In [173]:
def stop_word(text):
    stop_words=set(stopwords.words('english'))
    filtered=[
        word for word in text
        if word.lower() not in stop_words
    ]
    return filtered

In [ ]:
df['clean_review']=df['clean_review'].apply(stop_word)

## Stemming

In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()